title: Michelle Michael, Associate Data Analyst # your name (or website title) here
logo: "/images/photoid.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my Capstone Project 4 titled Machine Learning with Python. 
  <br><br>
  Python libraries used; Numpy, Pandas, Sklearn, Matplotlib, Pyplot and Seaborn. 
  <br><br>
  Pls click on arrows at the bottom right to view the project in full screen.
  <br><br>
  Feel free to contact me at <b>michellemichael123@gmail.com</b>
  <br><br>
  <a href="https://www.linkedin.com/in/example/" target="_blank">Or view my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
